name: trub-ai-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.104.1
  - uvicorn
  - librosa=0.10.1
  - numpy=1.24.3
  - scikit-learn=1.3.2
  - pydantic=2.5.0
  - python-multipart=0.0.6
  - pydub=0.25.1
  - aiofiles=23.2.1
  - pandas=2.1.3
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - joblib=1.3.2
  - ffmpeg  # Add this for audio processing
  - libsndfile  # Add this for audio file support
  - pip
  - pip:
      - noisereduce==2.0.0
      - soundfile==0.12.1
